metadata.format.version = "1.1"

[versions]

# plugins
shadow = "7.1.2"
blossom = "1.3.0"
licenser = "0.6.1"

# general
gson = "2.9.0"
annotations = "23.0.0"

# platform api versions
sponge = "9.0.0"
nukkitX = "1.0-SNAPSHOT"
minestom = "master-SNAPSHOT"
spigot = "1.8.8-R0.1-SNAPSHOT"

# platform extensions
paperLib = "1.0.7"
protocolLib = "master-SNAPSHOT"


[libraries]

# general
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }

# platform api
nukkitX = { group = "cn.nukkit", name = "nukkit", version.ref = "nukkitX" }
spigot = { group = "org.spigotmc", name = "spigot-api", version.ref = "spigot" }
sponge = { group = "org.spongepowered", name = "spongeapi", version.ref = "sponge" }
minestom = { group = "com.github.Minestom", name = "Minestom", version.ref = "minestom" }

# platform extensions
paperLib = { group = "io.papermc", name = "paperlib", version.ref = "paperLib" }
protocolLib = { group = "com.github.dmulloy2", name = "ProtocolLib", version.ref = "protocolLib" }


[plugins]

blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
licenser = { id = "org.cadixdev.licenser", version.ref = "licenser" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
